CREATE TABLE [dbo].[TB_TEAMS]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [Name] VARCHAR(50) NOT NULL UNIQUE,
    [Description] VARCHAR(256) NULL, 
    [Enabled] BIT NOT NULL DEFAULT 1,
    [Visibility] INT NOT NULL,
    [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(), 
    [UdpatedAt] DATETIME NOT NULL DEFAULT GETDATE(), 
    [DeletedAt] DATETIME NULL,
)
